extract-pds-churchoffice-data/email-queries.py
Some Python PDS email queries (that output in CSV) that are being used to help cleanup the parishioner listserve and our PDS database.  These likely won't be used a lot over time, but I'm saving them here for posterity / future examples.
=> Some PDS email queries.

extract-pds-churchoffice-data/email-queries.py
=> email-queries: add some more queries

internet-connectivity-checker/internet-connectivity-checker.py
=> conn checker: minor Windows fix

internet-connectivity-checker/internet-connectivity-checker.py
=> conn checker: fix typo in submission data

convert-gdrive-folder-to-team-drive/README.md, convert-gdrive-folder-to-team-drive/gxcopy.py
=> gxcopy.py: slightly simpler version of Team Drive migration

internet-connectivity-checker/internet-connectivity-checker.py
If we're offline, check every second.  Also update output messages.
=> conn checker: discover return to online faster

internet-connectivity-checker/internet-connectivity-checker.py
=> conn checker: print out the reason connectivity failed

media/linux/.gitignore, media/linux/export-pds-into-sqlite/.gitignore, media/linux/export-pds-into-sqlite/export-pdschurchoffice-to-sqlite3.py, media/linux/export-pds-into-sqlite/run.sh, media/linux/pds-sqlite3-queries/.gitignore, media/linux/pds-sqlite3-queries/pds-sqlite3-queries.py, media/linux/pds-sqlite3-queries/replace-parishioners.sh, media/linux/pds-sqlite3-queries/run.sh, media/linux/run-all.py
See descriptions in the commit messages.
=> Media server linux VM scripts

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: add Mp3 homebound ministry

media/linux/pds-sqlite3-queries/sync-google-group.py
Also add support for custom per-group notification email addresses.
Did not enable PPC sync yet because doing some dry runs shows that there's
still some discrepancies between PDS data and what's currently in the
PPC Google Group.
=> sync-google-group: add PPC

media/windows/email-timecard-twice-month/email-timecard.py
The script is working, so remove the tech committee from the To line.
Add Jim D and Faith M to the To line, since they're not in the "staff"
Google Group.
=> timecard: update the To list

media/windows/copy-mp3s-to-google-drive/find-and-copy.py
=> copy MP3s: remove FTP upload functionality

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-ggroup: enable SEL syncing

media/linux/pds-sqlite3-queries/sync-mailman.py
=> Make sure to check for an empty email list

media/linux/export-pds-into-sqlite/export-pdschurchoffice-to-sqlite3.py
Turns out that sometimes there's an SQL keyword inside a string, and
we don't want to add "pds" to the front of that.  So instead of using
simplistic regexp's to find SQL keywords, use a slightly more
complicated method.
=> export PDS->SQL: fix SQL keyword quoting

media/linux/pds-sqlite3-queries/sync-google-group.py, pds-queries/2018-summer-census-update/make-and-send-emails.py, pds-queries/2018-summer-census-update/no-hoh-or-spouse-email-report.py, python/ECC.py, python/GoogleAuth.py, python/PDSChurch.py
Convert sync-google-group.py to new PDSChurch.py module.  Lots less code!
=> More updates

media/windows/email-backup-thursday/backup-thursday.py, media/windows/email-patch-tuesday/patch-tuesday.py
These are automated emails, so sent them to the automated collection
point: itadmin@.
=> Automated emails: send to itadmin@, not tech-committee@

python/PDSChurch.py
Some comments, make a few things private, etc.  Just minor updates.
=> PDSChurch.py: minor updates

media/linux/pds-sqlite3-queries/sync-google-group.py
"ECC Liturgy Plans editor" and "ECC Liturgy Plans reader".
=> sync-google-group: add two more synchronizations

media/linux/pds-sqlite3-queries/sync-google-group.py
=> PDS Google Sync: Add Worship ministry

pds-queries/2018-summer-census-update/find-families-who-have-not-yet-replied.py
Output:
- number of families who replied
- number of families who did not reply
- one long comma-delimited line of envelope IDs of families who
replied (suitable for PDS queries)
- one long comma-delimited line of envelope IDs of families who
did not reply (suitable for PDS queries)
- the names of the files that we're writing to
=> find-families: updates to census queries

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add prayer chain mininstry

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: fix typo

pds-queries/2018-summer-census-update/make-and-send-emails.py
=> 2018 summer census: send final final final reminder

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add 31-Adult Choir

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: fix old variable name

media/linux/export-pds-into-sqlite/run.sh
=> export-pds-data: also backup the raw PDS data files

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-groups: add 10 Percent Emergency Assistance

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: add MOE

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Add Faith's email address for notifications

media/linux/pds-sqlite3-queries/sync-google-group.py
=> MOE: Add more to the MOE sync notifications

media/linux/pds-sqlite3-queries/sync-google-group.py
=> google-sync: Add EBM

media/linux/pds-sqlite3-queries/sync-google-group.py
Add more PDS<-->Google Group sync.
=> More Google Group Goodness

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Add keyword for bell choir list

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Add seamstresses ministry

convert-gdrive-folder-to-team-drive/convert.py, convert-gdrive-folder-to-team-drive/gxcopy.py, media/linux/pds-sqlite3-queries/sync-google-group.py, media/windows/copy-mp3s-to-google-drive/find-and-copy.py, pds-queries/2018-summer-census-update/compare-jotform-results-to-pds.py, pds-queries/2018-summer-census-update/find-families-who-have-not-yet-replied.py, python/ECC.py, python/Google.py, python/GoogleAuth.py
=> Google infrastructure-related updates

media/linux/export-pds-into-sqlite/run.sh, media/linux/google-drive-uploader/README.md, media/linux/google-drive-uploader/google-drive-uploader.py
We keep running out of space on our small Linux VM.  So store the PDS
data backups in a dedicated Google Team Drive, instead.
=> After making the nightly PDS archive, upload to Team Drive

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Add the wedding ministries keyword/group

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-groups: Add Liturgical planning

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: re-order and fix typos

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: add breadmakers

dmarc/process-dmarc-xml.py
=> First cut of DMARC XML-flattening script

dmarc/process-dmarc-xml.py
Including separate CSV files for each date.
=> dmarc: more tweaks

dmarc/process-dmarc-xml.py
=> dmarc: Minor tweaks to the script

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-goog-group: Add sages ministry

media/linux/pds-sqlite3-queries/sync-google-group.py
seamstresses@ecc --> healing-blankets-ministry@ecc
Also, Julie has now left ECC.  So don't send her notifications.
=> sync-google-group: rename sematresses

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add apply@ecc group

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Add pastoral/support staff

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Add funeral mass ministry

media/linux/export-pds-into-sqlite/run.sh, media/windows/copy-mp3s-to-google-drive/find-and-copy.py
Update to match the Google Team Drive -> Shared Drive re-branding.
=> "Team Drive" --> "Shared Drive"

pds-queries/2019-pds-log-to-csv/convert.py
There's an errant character in the PDSOffice.log file that will not
UTF-8 decode.  So we have to put an extra loop in there that tries to
UTF-8 decode it, and then skip it if it fails (because it's that one
bad line that we know/don't care about).
=> PDS log convert: updates to handle errant character

python/PDSChurch.py
=> PDSChurch.py: also include pledges

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-groups: Add 77-SVDP ministry

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-goog-group: Update for new PDS ministry numbers

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-goog-group: fix some typos

media/linux/export-pds-into-sqlite/export-pdschurchoffice-to-sqlite3.py
=> export-pds-data: minor updates

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-goog-groups: update some notification contacts

media/linux/google-drive-uploader/google-drive-uploader.py
=> google-drive-uploader: better error reporting

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, media/linux/pds-sqlite3-queries/run.sh, python/PDSChurch.py
=> Make ministry Google sheet rosters

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> rosters: Add Tech Committee

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add 101-LRP

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> rosters: add FAC

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
Also re-order the ministries to be in numerical order.
=> rosters: add 600-MOE

media/windows/copy-mp3s-to-google-drive/find-and-copy.py
Also add a helpful debug statement
=> mp3: fix python class typo

media/linux/README.md, media/linux/google-drive-uploader/README.md, media/linux/pds-sqlite3-queries/README.md
=> Various updates to README files.

media/linux/etc/postfix/README.md, media/linux/etc/postfix/main.cf
=> Notes to make Postfix work in Ubuntu 18.04 WSL

media/linux/etc/logrotate.d/epiphany.conf
=> Add Linux logrotate config file

media/windows/server-backups/google-backups.bat
=> Add the Ecobee data file to the Google backup files

media/linux/pds-sqlite3-queries/sync-google-group.py
Change to delete by ID (instead of by email address) because of a weird
corner case:
- foo@example.com (a non-gmail address) is in a google group,
but has no Google account
- later, foo@example.com visits
https://accounts.google.com/SignupWithoutGmail and gets a
Google account associated with that email address
In this case, Google seems to be somewhat confused: foo@example.com is
still associated with the Group, but it's the non-Google-account
foo@example.com.  But if we attempt to move that email address, it'll
try to remove the Google-account foo@example.com (and therefore fail).
So we remove by ID, and that unambiguously removes the correct member
from the Group.
=> sync-google: handle a corner case in deletion

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> Add a roster for 103-Worship Committee

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
Also update a few of the strings to use f''-style strings.
=> rosters: Add header row with the ministry name

media/windows/ECC-Ecobee/ECC Pycobee Data.py, media/windows/ECC-Ecobee/readme.md
ECC Ecobee Data, v03.05 release...@fowlerk, 24-Feb-2020
Reworked authentication token storage to use JSON-formatted file.  Added parsing of command-line arguments for files used by application.
Added database archival routine.  Resequenced Internet connectivity check routine.  Other minor bug fixes and code refactoring.
=> ECC Ecobee Data, v03.05 release / updated README

media/windows/ECC-Ecobee/requirements.txt
=> Add new ECC Ecobee requirement: dnspython

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-groups: Add 5 Formation ministries

media/linux/pds-sqlite3-queries/sync-google-group.py
1. Add Lisa to her ministries
2. s/erin/don/, since Erin is gone and Don is filling in
3. s/jeff@sq/pds-google-sync@{ecc}/ -- it's better to have a role for
this oversight email address (vs. an individual user email address)
=> sync-google-groups: multiple updates

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: fix typo in Lisa email address

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-groups: Add visual faith ministry

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add maintenance staff google group

pds-queries/2020-covid-wellness-checks/helpers.py, pds-queries/2020-covid-wellness-checks/make-spreadsheets.py
Write out to XLSX so that we can drag them into Google Drive and they
will convert -- with formatting intact -- to Google Spreadsheets.
=> First cut: COVID wellness checks spreadsheets

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, media/linux/pds-sqlite3-queries/create-training-rosters.py, media/linux/pds-sqlite3-queries/run.sh, python/PDSChurch.py
First attempt at create-training-rosters.py, similar to create-ministry-rosters but with PDS trainings instead.
=> First attempt at create-training-rosters.py.

media/windows/ECC-MQTT-IoT/ECC_MQTT_IoT_SQLite.py, media/windows/ECC-MQTT-IoT/readme.md
This is the initial release of the Epiphany MQTT IoT Listener (v01.20).
=> ECC MQTT IoT Listener - Initial Release

media/linux/run-all.py
=> run-all: also pass the environ to subprocess

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, pds-queries/2021-stewardship/README.md, pds-queries/2021-stewardship/constants.py, pds-queries/2021-stewardship/copy-while-running.zsh, pds-queries/2021-stewardship/email-1st-reminder.html, pds-queries/2021-stewardship/email-2nd-reminder.html, pds-queries/2021-stewardship/email-3rd-reminder.html, pds-queries/2021-stewardship/email-4th-reminder.html, pds-queries/2021-stewardship/email-initial.html, pds-queries/2021-stewardship/email-test.html, pds-queries/2021-stewardship/email-thank-you-and-survey.html, pds-queries/2021-stewardship/helpers.py, pds-queries/2021-stewardship/make-and-send-emails.py, pds-queries/2021-stewardship/nightly-reports.py, pds-queries/2021-stewardship/php/error.php, pds-queries/2021-stewardship/php/index.php, pds-queries/2021-stewardship/php/stale.php, pds-queries/2021-stewardship/php/unknown.php, pds-queries/2021-stewardship/pledge-fullfillment-report.py, pds-queries/2021-stewardship/send-thank-you-emails.py
1. Create skeleton for 2021 eStewardship
1. Add PPC to the list of generated rosters
=> Two updates

pds-queries/2021-stewardship/README.md, pds-queries/2021-stewardship/constants.py, pds-queries/2021-stewardship/copy-while-running.sh, pds-queries/2021-stewardship/make-and-send-emails.py, pds-queries/2021-stewardship/nightly-reports.py, pds-queries/2021-stewardship/php/index.php, pds-queries/2021-stewardship/print-member.py, pds-queries/2021-stewardship/run.bash, pds-queries/2021-stewardship/send-thank-you-emails.py
First set of updates for 2021 eStewardship.  There will be many more.
=> Lots of updates for eStewardship 2021

pds-queries/2021-stewardship/constants.py, pds-queries/2021-stewardship/make-and-send-emails.py, pds-queries/2021-stewardship/run.bash
=> stewardship 2021: minor tweaks

pds-queries/2021-stewardship/email-initial.html, pds-queries/2021-stewardship/email-thank-you-and-survey.html
Updates email-initial and email-thank-you-and-survey
=> 2021 stewardship email updates

pds-queries/2021-stewardship/constants.py, pds-queries/2021-stewardship/make-and-send-emails.py, pds-queries/2021-stewardship/run.bash
Add a bunch of "JMS2021" comments about what I think we need to do to
make_and_send_emails.py and constants.py for the 2021 stewardship drive.
=> 2021 stewardship: comments about what we need to do

pds-queries/2021-stewardship/make-and-send-emails.py
=> 2021 stewardship: minor tweaks

media/windows/copy-mp3s-to-google-drive/find-and-copy.py
=> upload MP3s: fix typo

python/ECC.py
Use the Linux syslog (which will end up at the journald on modern
Linux distros) or the Windows Event Log, if available.
=> ECC.py: use system loggers

media/windows/ECC-MQTT-IoT/ECC_MQTT_IoT_SQLite.py, media/windows/ECC-MQTT-IoT/readme.md
Signed-off-by: fowlerk <keith.fowler.kf@gmail.com>
=> ECC MQTT IoT Listener - Release v02.00

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Add 451-Livestream Team ministry

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: update 10% leadership PDS ministry name

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: rename some Google Groups

media/linux/pds-sqlite3-queries/sync-google-group.py, python/ECC.py
=> Several updates

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Update livestream team contact address

pds-queries/2021-stewardship/constants.py, pds-queries/2021-stewardship/make-and-send-emails.py, pds-queries/2021-stewardship/run.bash
Minor updates for the 1st reminder email for eStewardship 2021.
=> 2021 eStewardship: minor updates

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: add Tom to livestream team notifications

pds-queries/2021-stewardship/constants.py, pds-queries/2021-stewardship/make-and-send-emails.py, pds-queries/2021-stewardship/nightly-reports.py, pds-queries/2021-stewardship/run.bash
Starting to work on reports / importing data into PDS.
=> More updates for eStewardship 2021

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: change MOE ownership

python/ECC.py
=> ECC.py: fix the FileHandler logging module name

pds-queries/2021-stewardship/make-and-send-emails.py, pds-queries/2021-stewardship/nightly-reports.py, pds-queries/2021-stewardship/run.bash
- re-enable statistics/comments reports
- re-enable JMS email addresses for safety
- send 3rd reminder
=> 2021 eStewardship: next round of updates

pds-queries/2021-stewardship/nightly-reports.py
=> More stewardship tweaks

pds-queries/2021-stewardship/nightly-reports.py
=> eStewardship: add another column in Comments report

pds-queries/2021-stewardship/email-5th-reminder.html, pds-queries/2021-stewardship/run.bash
=> eStewardship: record of 5th reminder email

pds-queries/2021-stewardship/nightly-reports.py, python/PDSChurch.py
Change up the ministry human review report.  Load a few new
capabilities / fields to Member dictionary in PDSChurch.py.
=> eStewardship: staff-requested report changes

pds-queries/2021-stewardship/nightly-reports.py
=> eStewardship 2021: update status and pledge reports

pds-queries/2021-stewardship/nightly-reports.py, python/PDSChurch.py
=> eStewardship: a few more tweaks to the pledge report

media/linux/pds-sqlite3-queries/sync-google-group.py, python/PDSChurch.py
=> Small tweaks

pds-queries/2021-stewardship/squish-ministry-sheets-into-one.py
=> eStewardship: more report tweaks

pds-queries/2020-covid-wellness-checks/make-spreadsheets.py, pds-queries/2020-covid-wellness-checks/requirements.txt, pds-queries/2021-stewardship/interested-ministry-spreadsheets.py, python/PDSChurch.py
Updates to 2021 stewardship reports (i.e., generate the "interested" ministry spreadsheets), and minor tweaks for the COVID wellness checkup spreadsheets.  See individual commit messages for more details.
=> Reports updates

media/windows/calendar-reservations/.gitignore, media/windows/calendar-reservations/calendar-reservations.py, media/windows/calendar-reservations/requirements.txt
A bot that accepts pending Google Calendar events from users with Epiphany
email domains that do not conflict with other events, and declines all other
events. It iterates through a list of all Epiphany calendars, downloading all
events. Then it checks the domain of the event creator's email, declining if
it is a non-Epiphany domain. For all events with acceptable creators, it checks
whether the event conflicts with other events on the calendar, accepting ones
that do not and declining ones that do.
Signed-off-by: Victoria Cabral <43216482+toQhom@users.noreply.github.com>
=> calendar-reservations: First working copy

pds-queries/2020-covid-wellness-checks/make-spreadsheets-narrow.py
Split into English and Spanish household sheets, and also target a
specific number of sheets to produce (i.e., that's how many volunteers
we have, so make exactly that number of sheets).
=> Update COVID wellness spreadsheet script

pds-queries/2020-covid-wellness-checks/make-spreadsheets-narrow.py, pds-queries/2021-stewardship/nightly-reports.py
=> Minor report tweaks

media/linux/pds-sqlite3-queries/requirements.txt, media/linux/pds-sqlite3-queries/sync-google-group.py, python/GoogleAuth.py
See individual commit messages for more details.
=> Miscellaneous updates

media/windows/ECC-Ecobee/ECC Pycobee Data.py, media/windows/ECC-Ecobee/readme.md
Several minor modifications for v03.11 release:
Modified to add support for new thermostat attributes for 'audio','energy', and
'filter_subscription', even though we're not requesting these in the selection
request for the thermostat details.
Clarified output message where the latest database runtime data is equal to or greater
than the latest revision interval data returned from the Ecobee service for thermostat
details.
Also corrected bug in processing of GMail credentials file and included some missing
imports for the new mail routine for error-aborts.
=> Signed-off-by: fowlerk <keith.fowler.kf@gmail.com>

media/linux/pds-sqlite3-queries/run.sh, media/linux/pds-sqlite3-queries/sync-google-group.py, media/linux/run.sh, python/ECC.py
Update sync-google-group.py to use it, and also add a few additional updates to sync-google-group.py.  See individual commit messages for more details.
=> Add send-email functionality to ECC.py

media/linux/pds-sqlite3-queries/ppc-feedback-google-group.py, media/linux/pds-sqlite3-queries/run.sh, python/GoogleAuth.py
Use a Google Sheet to update the members of ppc-feedback@ecc according
to a date schedule.
=> ppc-feedback: sync membership of ppc-feedback@ecc

media/windows/ECC-MQTT-IoT/ECC_MQTT_IoT_SQLite.py, media/windows/ECC-MQTT-IoT/readme.md
Added logic to support additional fields received from the new sensor code,
including location, MAC address, and software version.  These fields will be
added to a new table in the database, but only if the data changes from the
last-recorded information.
Signed-off-by: fowlerk <keith.fowler.kf@gmail.com>
=> ECC MQTT IoT Listener - Release 02.30

media/linux/.gitignore, media/linux/export-pds-into-sqlite/export-pdschurchoffice-to-sqlite3.py, media/linux/export-pds-into-sqlite/run.sh, media/linux/google-drive-uploader/google-drive-uploader.py, media/linux/pds-sqlite3-queries/.gitignore, media/linux/pds-sqlite3-queries/run.sh, media/linux/pds-sqlite3-queries/sync-google-group.py, media/linux/run-all.py, media/linux/run.sh
=> Updates for Linux Python automation

media/linux/pds-sqlite3-queries/run.sh
Fix a mistake in a credential filename.
=> pds-sqlite-queries: fix a credential filename

media/linux/google-drive-uploader/google-drive-uploader.py
=> google-drive-uploader: add missing --logfile

media/linux/google-drive-uploader/google-drive-uploader.py
=> google-drive-uploader: be sure to to return the new args

media/linux/export-pds-into-sqlite/run.sh, media/linux/run-all.py
=> Tweaks to Linux "run-all"

media/linux/ricoh/run.sh
=> ricoh: add date/timestamp into output CSV filename

pds-queries/2021-stewardship/README.md
Update the README.md with all the details from this year's campaign.
=> 2021 eStewardship: update README.md

pds-queries/2021-stewardship/README.md
Argh -- merged too soon: missed these edits in the README.md file.
=> eStewardship 2021: missed README edits

python/PDSChurch.py
Gmail does two special things with email addresses:
1. If the left hand side contains a ".", ignore it.
2. If the left hand size contains a "+BLAH" suffix, ignore it.
Meaning that the following email addresses all resolve to the same
Google account:
- foobar@gmail.com
- foo.bar@gmail.com
- f.o.o.b.a.r@gmail.com
- foobar+hello@gmail.com
- foobar+whazzup@gmail.com
- foo.bar+new-phone-who-dis@gmail.com
This means that we can give any of these email addresses to Google and
it will resolve them to foobar@gmail.com.
The problem is if we query a Google Group and it tells us that
"foobar@gmail.com" is a member, but we have "foo.bar@gmail.com" in
PDS.  Previously, the Python would treat these as two different email
addresses.
This commit changes it so that when we read in Google email addresses …
=> PDSChurch.py: normailze gmail addresses

media/linux/pds-sqlite3-queries/sync-google-group.py, python/PDSChurch.py
Google didn't behave the way I expected.  😦 
So use a different approach.  See the individual commit messages for more details.
=> Fix the gmail normalization

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> create-ministry-rosters: Add more ministries

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, media/linux/pds-sqlite3-queries/sync-google-group.py
=> Add Community Life ministry

media/linux/pds-sqlite3-queries/sync-google-group.py
Also use the official minister email address for notifications.
=> sync-google-groups: Add more Social Resp ministries

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> ministry rosters: add Sages ministry

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add registration@ecc keyword

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, pds-queries/2021-stewardship/print-member.py, python/PDSChurch.py
This kind of functionality is used in multiple places, so we might as
well put it in PDSChurch.py.
=> PDSChurch.py: add some common query functions

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add renovations@ecc email list

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: Linda retirement planning group

python/PDSChurch.py
When loading Member ministries and classifying them into the active /
inactive lists in the Python Member dictionary, make sure to take the
start/end dates into account.  This is important for ministries that
have defined term lengths (i.e., a Member will have a specific start
date and a specific end date).
For example, it is possible that a Member is recorded as "Active" in a
Ministry, but their start date is in the future (e.g., their term
doesn't start for another month).  In this case, this ministry should
be on the Member's inactive ministry list.
Similarly, it is possible that a Member is recorded as "Active", but
today's date is past the end date.  This case should also place the
ministry entry on the Member's inactive ministry list.
=> PDSChurch.py: obey Member ministry start/end dates

media/linux/pds-sqlite3-queries/sync-google-group.py
=> Add new Director of Worship to email notifications

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> create-ministry-roster: Add several youth ministries

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add 404 Welcome Desk ministry

media/linux/pds-sqlite3-queries/create-training-rosters.py, media/linux/pds-sqlite3-queries/training_sheets.py, python/PDSChurch.py
Integrates the second round of changes to pr/training-rosters.
=> Pr/training rosters (Round 2)

media/linux/pds-sqlite3-queries/create-training-rosters.py, media/linux/pds-sqlite3-queries/sync-google-group.py, python/PDSChurch.py
See individual commit messages for more detail
=> Random python fixups

media/linux/pds-sqlite3-queries/sync-google-group.py
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>
=> sync-google-group: remove deleted group

media/linux/pds-sqlite3-queries/sync-google-group.py
The last commit contained a typo.  This is why we should test before
we merge PRs.  :-(
=> sync-google: fix typo

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> create-ministry-rosters: delete obsolete ministries

media/linux/run-all.py
If the lockfile was created over an hour ago (and still exists), that
almost certainly means something is wrong.  Alert a human by emitting
to log.error (which will get logged to Slack).
=> linux/run-all.py: check lockfile age

media/linux/pds-sqlite3-queries/sync-google-group.py
Minor updates in who gets some of the emails to reflect personnel
changes.
=> sync-google-group: update some CC's

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: new google group

pds-queries/2022-stewardship/constants.py, pds-queries/2022-stewardship/nightly-reports.py
=> Fix some 2022 stewardship typos

media/linux/calendar-reservations/calendar-reservations.py
=> calendar-reservations.py: Add Polycom calendar

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-groups: add worship-chair@ecc

pds-queries/2021-stewardship/squish-ministry-sheets-into-one.py, pds-queries/2022-stewardship/nightly-reports.py, pds-queries/2022-stewardship/squish-ministry-sheets-into-one.py
=> Misc stewardship updates

pds-queries/2022-stewardship/interested-ministry-spreadsheets.py
Find all Members in PDS listed as "interested" in a given ministry and
put them in spreadsheets.  Ministry leaders will use these sheets to
contact the interested Members for CY2022.
=> 2022 stewardship: generate the final "interested" sheets

mary/analysis/financial-analysis.py, mary/analysis/requirements.txt
=> FAC analysis: minor updates for 2021

pds-queries/2022-stewardship/convert-sheets-to-pdf.py
=> eStewardship 2022: minor updates to convert-to-PDF script

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, media/linux/pds-sqlite3-queries/sync-google-group.py
See individual commit messages
=> sync-goog: various updates

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, media/linux/pds-sqlite3-queries/sync-google-group.py, python/PDSChurch.py
=> google: Add 300 Art&Environment ministry

media/linux/pds-sqlite3-queries/create-communion-ministry-reports.py, media/linux/pds-sqlite3-queries/run.sh
=> Communion minister reporting tweaks

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> create-ministry-rosters: add 4040 Welcome Desk

media/linux/pds-sqlite3-queries/create-ministry-rosters.py, pds-queries/utilities/requirements.txt
See the individual commit messages for details.
=> Make PDS rosters for all the active ministries

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> create-ministry-rosters: fix broken URL

media/linux/ricoh/report.py
If not specified, use the earliest and most recent timestamps found in
the database as the first and last timestamp, respectively.
=> ricoh report: default first and last timestamps

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add 508 Messages of Hope

media/linux/pds-sqlite3-queries/sync-google-group.py
Also a little code shuffle/re-org to group some similar items
together.
=> sync-goog-group: Add 401 Epiphany Companions Chair

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add stewardship-name-badges-google-drive-access@ecc

media/linux/pds-sqlite3-queries/gsheet-driven-google-group.py, media/linux/pds-sqlite3-queries/run.sh
Generalize the "ppc-feedback" script to be able to handle multiple
Google Sheets / Google Groups.  Add a 2nd group: fac-feedback@ecc.
=> Google Sheet-driven Google Group membership

media/linux/google-drive-uploader/README.md, media/linux/google-drive-uploader/google-drive-uploader.py
Minor updates and fixes to address some bit rot in the Google Drive
Uploader python script.
=> google-drive-uploaded.py: fix some bit rot

pds-queries/2022-census/process-census-results.py
Some updates to the reporting for PDS / manual imports for 2022 Census.
=> 2022 Census: updates

media/linux/ricoh/report.py
Add two columns for each department:
- this department's percentage of the overall B&W prints/copies in
this time range
- this department's percentage of the overall color prints/copies in
this time range
We add these columns because of a discovery we made this month:
Duplicator Sales (our Ricoh maintenance vendor) charges us monthly
based on the Meter History of the Ricoh.  This Meter History is from
the "Counter" report on the Ricoh, and it represents the total usage
since the beginning of the life of this printer.
Sidenote: Duplicator Sales records the Meter History counter
values on the 8th of each month (it's an automated process).
Every night, ECC downloads the "Counter by User" CSV, which is a
point-in-time reporting of all kinds of statistics (including total
B&W and total color) …
=> ricoh/report.py: add percentag columns

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: add Worship/Art&Env chair

media/linux/pds-sqlite3-queries/create-communion-ministry-reports.py
Make a Google Sheet with the union of all Active PDS Members who have
a current communion minister mandate.
=> communion-minister: add another report

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add sel-chair@ecc

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: SEL updates should go to Lynne Webb

media/linux/pds-sqlite3-queries/sync-google-group.py
Update Python code to match all the PDS ministry renames that ocurred
in September, 2022 as part of the preparation for eStewardship.
=> sync-google-group: 2022 PDS ministry renames

media/linux/pds-sqlite3-queries/sync-google-group.py, pds-queries/utilities/print-member.py
=> Minor updates

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google: add Community Life and MOE chairs

media/linux/run-all.py
In Oct 2022, about once a day, some run.sh script started hanging indefinitely.  Specifically, there will be a child "awk" process of export-pds-into-sqlite/run.sh, and the awk process will complete and go into a zombie state. However, the parent run.sh script apparently does not recognize that the child is now zombied and needs to be reaped.  It sits, forever. This means that the subsequent invocation of run-all.py will fail to get the lockfile.  Eventually, it will start sending error messages to Slack because the lockfile from the still-hung run-all.py will become too old.
This parent-does-not-reap-a-child-zombie behavior very much feels like a bug in WS2019/WSL1.  Indeed, I do not even see anywhere where the code from this tree invokes "awk" -- that's a bit of a mystery in itself.
For …
=> run-all.py: workaround Oct 2022 WS19/WSL1 errors

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: add 113 Communications ministry

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add director-choir@ecc

media/linux/pds-sqlite3-queries/sync-google-group.py
=> Aux staff and wedding assistant chair

media/linux/pds-sqlite3-queries/sync-google-group.py
=> sync-google-group: Add 407 Stewardship Team

media/linux/internet-connectivity-checker/internet-connectivity-checker.py, media/linux/pds-sqlite3-queries/sync-google-group.py, media/linux/upload-mp3s-to-google-drive/run.sh, media/linux/wsl/setup-wsl.sh, pds-queries/2023-stewardship/nightly-reports.py
Minor touchups plus some changes from discussions with staff today.
=> A few random touchups

media/linux/pds-sqlite3-queries/sync-google-group.py
Add both ministry and chair groups.  Also update one stale notification target.
=> sync-google-group: Add 501 Care of the sick

media/linux/pds-sqlite3-queries/create-communion-ministry-reports.py
* No longer create the 313x sub-ministry reports
* Add a "Notes" column to the "All parishoiners with a current Communion Minister mandate" sheet, and note in there if the mandate expires in the next 6 months
=> communion-minister-reports.py: updates

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
=> create-ministry-rosters: fix 318 lectors name

media/linux/calendar-reservations/calendar-reservations.py
This calendar was just deleted / this table is no longer reservable.
=> calendar-reservations: remove CN table 3

pds-queries/2023-census/process-census-results.py
I think this code was left over from the first year that we did mass keywords in census -- it just showed *all* the existing Family mass keywords.  This commit updates the code to show only the *changes* in Family mass keywords (similar to all other census data reporting).
=> census: show only changes in the Family mass keywords

python/ECCEmailer.py
Generalized emailer script for use in Epiphany projects
=> Add ECCEmailer

media/linux/pds-sqlite3-queries/sync-google-group.py
Ministry moves and renames for the upcoming 2023 Stewardship drive.
=> sync-google-group: updates for 2023 Stewardship

python/PDSChurch.py
These fields are being checked as part of the conversion to ParishSoft.
=> PDSChurch: add some more PDS fields

pds-queries/utilities/print-member.py, python/PDSChurch.py
=> Additional PDS data

media/linux/ricoh/report.py, python/ECCEmailer.py, python/ECCUploader.py, python/Google.py, python/GoogleAuth.py
Automates report.py in ricoh to no longer need manual start or end dates.
=> Automate Ricoh reports

media/linux/ps-queries/sync-google-group.py, ps-queries/utilities/print-member.py, ps-queries/utilities/print-ministries.py
=> Add new google groups

media/linux/calendar-reservations/calendar-reservations.py
* Rename "Kitchen" to "Commercial Kitchen"
* Add "Service Kitchen"
=> calendar-reservations: update CC kitchen rooms

media/linux/ps-queries/sync-google-group.py, python/ParishSoftv2.py
=> Handle new Google result message

media/linux/ricoh/report.py, media/linux/ricoh/requirements.txt, media/linux/ricoh/run.sh, media/linux/upload-mp3s-to-google-drive/find-and-copy.py
We previously developed monthyl, quarterly, and annual Ricoh reports.  However, it turns out that this is not what is needed.  All we need is. a monthly report.  So return to the monthly report logic, and add the functionality of automatically uploading it to Google and sending an email when the upload is complete.
=> Automate ricoh reporting

media/linux/ricoh/run.sh
This was accidentally left off the last PR.
=> ricoh: fix errors in shell script

media/linux/upload-mp3s-to-google-drive/find-and-copy.py, media/linux/upload-mp3s-to-google-drive/requirements.txt
- Remove some dead code
- Convert a few old-style .format strings to f strings
- Add a big red notice to the result email when we upload a file that is over 100MB
=> upload mp3s: cleanups and add a notice about large files

.github/workflows/ecobee-google-calendar-control.yaml
Need to put an empty action here so that a PR modifying it will be able to be run in debugging mode.
=> Add a GitHub action for running Ecobee controls

media/linux/ecobee-control/data/config.json, media/linux/ecobee-control/src/ecobee/ecobee_client.py
Added check for access token expired to calls to Ecobee service for token refresh.
=> Added check for access token expired to calls to Ecobee service

media/linux/ecobee-control/src/ecobee/ecobee_client.py
Increased timeout value for all Ecobee service calls to 30 seconds due to periodic timeout failures.
=> Increased timeout value for all Ecobee service calls to 30 seconds

media/linux/aws/ecc.service, media/linux/aws/ecc.timer, media/linux/calendar-reservations/calendar-reservations.py
=> Calendar reservation fixes and some notes
