internet-connectivity-checker/internet-connectivity-checker.py
The script will ping google.com once a minute.  When it detects that it can't reach google, it records an outage start timestamp.  When it can finally ping google again, it submits a the outage start/stop timestamps to a Google Form (where the data can be analyzed later).
=> internet-connectivity-checker: save outages in a Google Form

internet-connectivity-checker/internet-connectivity-checker.py
Ping traffic turns out to not be reliable enough as a connectivity checker.  So let's use an HTTP GET of a super short web page (the GitHub.com status JSON) instead.
=> conn checker: ping is unreliable; check via HTTP GET

media/windows/copy-mp3s-to-google-drive/find-and-copy.py
Instead of "{a}{b}{c}.format(b=os.path.sep, ...)".
=> python: use os.path.join()

media/windows/email-timecard-twice-month/email-timecard.py
The hourly workers have a different timecard schedule than the
non-hourly workers.
=> timecard: change of plan: do *not* put hourlies on timecards

media/linux/pds-sqlite3-queries/sync-google-group.py, pds-queries/2018-summer-census-update/compare-jotform-results-to-pds.py, pds-queries/2018-summer-census-update/make-and-send-emails.py, python/PDSChurch.py
Don't return None if no emails are found; instead, return an empty
list.  This simplifies processing at the callers.
=> PDSChurch.py: always return a list from find_*_email()

pds-queries/2018-summer-census-update/compare-jotform-results-to-pds.py
Just like how we handle members to have been deleted, also allow
families to have been deleted.
=> 2018 census: allow families to have been deleted

media/linux/export-pds-into-sqlite/run.sh
Once a day, save a copy of the resulting pdschurch.sqlite3 file
in an archive directory.
=> export pds: save archives once a day

media/linux/ecc-clear-pds-lockfile.service
Upon machine reboot, remove the PDS synchronizer lockfile (just in
case the machine was rebooted/froze/whatever while the lockfile
was still present).
=> media/linux: systemd service to remove stale lockfile

media/windows/copy-mp3s-to-google-drive/find-and-copy.py
As of 1 Nov 2018, the MP3 recorder apparently spontaneously decided to
rename the MP3 files: they used to start with Rxxx, now they start
with Txxx.  Update the regexp to just ignore the first character of
the filename.
=> upload mp3s: update inbound file name mask

meraki-api/index.php
PHP no longer uses HTTP_RAW_POST_DATA; use php://input, instead.
=> meraki: fix webhook

media/windows/calendar-audit/calendar-audit.py
It turns out that Google Calendar audit data is only saved (at Google)
for 6 months.  Sometimes we need to go back farther than 6 months to
figure out what went wrong with Google Calendar issues (e.g., whether
someone accidentally deleted a Calendar event, etc.).  So have a
relatively simple Python job to run the Google Calendar audit report
and upload all the resulting JSON to a dedicated Google Team Drive.
Note that the Calendar audit data contains *ALL* Google Calendar data
for the entire G Suite domain -- even activity on individual /
personal calendars.  Hence, we default to saving this JSON in a
dedicated, highly-restricted-access Team Drive (i.e., not accessible
to the Tech Committee and not accessible to the general staff).
Note that we save the raw JSON (vs. converting it to …
=> calendar-audit: download/save Google Calendar audit data

media/linux/pds-sqlite3-queries/sync-google-group.py
Make the logging a little less verbose so that it takes up less room
over time.  Also, specifically denote one of the items as an error
(because technically it is a Google API error).
=> sync-google-group: turn down the logging

media/linux/pds-sqlite3-queries/sync-google-group.py
Only output debugging logging if --debug is specified.  A typo (or old
developement set?) was outputting debugging logging even when we only
specified --verbose (not --debug).
=> sync-google-group: fix debug argument

media/windows/copy-mp3s-to-google-drive/find-and-copy.py
If we have already copied the file to the archive (perhaps even
partially), remove it so that shutil.move() does not fail (it will fail
if the destination already exists).  I.e., we want to take the most
recent copy from incoming and put it in the archive.
=> find-and-copy: ensure existing archive is removed

media/linux/postfix/README.md, media/linux/postfix/main.cf
Notes and Postfix relay configuration for enabling Konica Minolta "scan to
email" functionality.
=> Postfix: relay configuration

media/linux/pds-sqlite3-queries/sync-google-group.py
Suppress emailing notices about backend Google errors -- but still log
them.  These errors just happen periodically (a few times a week).
There's no need to alert ministry leaders about them -- they're
periodic errors and if there was any action to do, it'll just get
picked up the next time the script is run.
=> sync-google: ignore backend Google errors

media/windows/server-backups/google-backups.bat
This script is run via the Windows Task Scheduler, once a day.  It
copies a bunch of folders from \\media-o3020 to C:\Epiphany_backups.
The C:\Epiphany_backups folder is synchronized out to Google Drive via
Google Backup and Sync.
Effectively, we're making a daily sync of these local folders to a
folder where Google Backup and Sync then synchronizes any changes up
to our backups in Google Drive.
=> Batch file to backup files on \\media-o3020

pds-queries/2019-pds-log-to-csv/convert.py
Convert the tab-separated PDSOffice.log file into PDSOffice.csv, which
is suitable for opening by Excel / Google Sheets.
=> PDS Office log conversion to a CSV file

meraki-api/index.php
According to https://www.sqlite.org/wal.html, use WAL mode for opening
sqlite3 so that we do not run into locking issues when multiple Meraki
REST calls arrive nearly simultaneously.
=> Meraki API index.php: fix periodic locking errors

media/linux/export-pds-into-sqlite/export-pdschurchoffice-to-sqlite3.py
PDS Church 9.0G has a dozen or two tables where the PXView table name
does not match the table filename.  E.g., Mem.DB has an internal
tablename of "resttemp.DB".
Even worse, all of these irregularly-named tables are "resttemp.DB".
Add a search/replace to change "resttemp.DB" to go back to the table
filename.
=> export PDS: fix SQL from PDS Church 9.0G

pds-queries/2019-fix-pds-photo-filenames/README.md, pds-queries/2019-fix-pds-photo-filenames/find-bad-picture-files.py, pds-queries/2019-fix-pds-photo-filenames/fix-family-picture-files.py, pds-queries/2019-fix-pds-photo-filenames/fix-member-picture-files.py
Fix PDS Member/Family photo filenames to reflect moving the "Z" drive
from \\fileengine (which was mapped to "Z:\" on all machines) to a
Google Shared Drive.  Do this by emitting a CSV with the new filename
location, mapped to a PDS Member MID or PDS Member FID, respectively.
See the README.md for more information.
=> Emit CSVs that can be imported into PDS

media/linux/export-pds-into-sqlite/run.sh
With the addition of more data exported from PDS, it was taking longer
than 5 minutes to finish, and the test for checking for "< 12:05am"
was never succeeding, and PDS data was not being backed up to Google
Drive.
So expand this test to check for "<= 12:14am".  This should be more
than enough to make sure that the backups now actually run.  Our PDS
exports run every 15 minutes, so this is still a safe test.
=> export-pds: do backups at <= 12:14am

media/windows/copy-mp3s-to-google-drive/find-and-copy.py, media/windows/internet-connectivity-checker/internet-connectivity-checker.py
The "recordclass" module is proving difficult to install with Python
3.8.1 and Visual Studio 19 on the media-o5020 server.  So just stop
using recordclass and use a regular Python class, instead.
=> Updates for media-o5070

media/linux/etc/README.md, media/linux/etc/sudoers, media/linux/export-pds-into-sqlite/run.sh
The "new" media server has become media-o3020 (even though it is an
Optiplex 5070, not a 3020 -- but we chose to keep the old name rather
than update it everywhere that name is used).  So now the Linux Python
on this server can access the files directly through /mnt/c (not a
network share mount).
=> Move PDS data to the "new" media server

media/linux/etc/postfix/main.cf
This seems to make it work in Ubuntu 18.04/WSL.
=> postfix: another round of relay fixes

media/windows/server-backups/google-backups.bat
Use /y so that xcopy always overwrites the destination without prompting.
=> server-backups: xcopy always overwrite

media/linux/export-pds-into-sqlite/export-pdschurchoffice-to-sqlite3.py
In my WSL environment the .exit command throws a syntax error if it is not on a line by itself.  Media might throw an error too.
If the last DB processed creates a transaction, then it will do an 'END TRANSACTION;\n'.  The \n will put the .exit on the next line and it works.  But, if the last DB drops out from the skip/ignore cases, then the .exit will be on the same line (causing a syntax error).  In either case, the extra newline is just white space and ignore during SQL processing.
Signed-off-by: Bruce Schweinhart <bswine2@gmail.com>
=> BLS:  Make sure the ".exit" command is on it's on line.

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
If there are no preferred email addresses, show the alphabetic first
non-preferred email address.
=> rosters: show a non-preferred email address if necessary

media/linux/pds-sqlite3-queries/sync-google-group.py
Add new keyword for ECC Musicians Info Editor, and mark ECC Sheet
Music to be deleted in the future.
=> sync-goog-group: updates

media/linux/etc/postfix/README.md, media/linux/etc/postfix/main.cf
Add some more documentation and explanation on the Postfix setup for
relaying out to Gmail.
=> Postfix: add more docs / explanation

media/linux/.gitignore, media/linux/pds-sqlite3-queries/.gitignore, media/linux/pds-sqlite3-queries/run.sh, media/linux/pds-sqlite3-queries/sync-google-group.py
We don't pay for a static IP address at ECC, and over the past several
weeks, it has changed several times.  As such, mails stopped flowing
until we noticed the IP address change and updated Google config to
match the new IP.
Instead of relying on a fixed/whitelisted IP address, use SMTP AUTH to
login with a valid set of ECC Google Account credentials, which will
allow us to send then send from *any* @epiphanycatholicchurch.org
email address.
NOTE: The Google Account email address used to SMTP AUTH must specify
a 2FA app-specific password as the SMTP AUTH password.  I.e., go to
that ECC Google Account in the Security setup and setup an
app-specific password, and then use that app-specific password here.
=> sync-google: use SMTP AUTH for sending email

media/linux/pds-sqlite3-queries/run.sh, media/linux/pds-sqlite3-queries/sync-google-group.py, media/windows/copy-mp3s-to-google-drive/find-and-copy.py, media/windows/email-patch-tuesday/patch-tuesday.py, media/windows/email-timecard-twice-month/email-timecard.py
Missed a bunch of other scripts that require converting to use SMTP
AUTH.  Change all of them to accept an --smtp-auth-file FILENAME
argument; the file is assumed to be a single line long and of the
format "username:password", where:
* username: ECC Google Account to use to login
* password: 2FA app-specific password for that account
=> Convert all Python to SMTP AUTH

media/linux/etc/postfix/README.md, media/linux/etc/postfix/main.cf
Update comments and notes about how we relay email out to
smtp-relay.gmail.com from the media server WSL Ubutunu instance.
=> smtp gmail postfix: update notes

media/linux/pds-sqlite3-queries/sync-google-group.py, pds-queries/2021-stewardship/constants.py
Remove some old ministries, rename some ministries, etc. as a result
of the annual staff update to the overall ministry list.
=> sync-google: annual ministry update

python/PDSChurch.py
We had another case this past week where an email address in PDS
contained a leading space, which led to mayhem when trying to
synchronize PDS addresses to Google Groups.  Add code here in
PDSChurch.py to trim all leading and trailing whitespace from email
addresses to prevent this problem from occurring again.
=> PDSChurch.py: trim whitespace from email addresses

python/PDSChurch.py
This field corresponds to the "Non-parishioner" checkbox in PDS10.
This is a Family field, not a Member field.
When reading the PDS SQLite3 database, filter non-parishioners if
their envelope number is > 10,000 *or* if their Visitor value is
true.
=> PDSChurch.py: support Family "Visitor" field

media/linux/pds-sqlite3-queries/sync-google-group.py
Some staff have moved around: update the email addresses that are
notified when various ministries are updated.
=> sync-google: update some staff email addresses

media/linux/etc/logrotate.d/epiphany.conf
The ECC MQTT Listener Python script runs in Windows, and the
logrotater runs in Linux.  Weird Things happen when you have a Linux
process rename/edit/delete a file that is open in Windows and is
supposed to be locked by the Windows filesystem.
This is different for the MQTT Listener (vs. our other Python codes)
because the MQTT Listener is running (and logging) 24/7, whereas the
other ECC Python scripts run, log, and then complete/exit.  In the
non-24/7 scenarios, if the logrotater comes in an
moved/renames/compresses the logfile, the next time the Python script
runs, it will just create a new logfile of the same name.  In the 24/7
case, if the logfile is moved/deleted while an active Windows Python process
is still writing to it, the Windows Python process will be unable to
log new …
=> logrotate: do not logrotate the ECCMQTT logfile

pds-queries/2021-stewardship/nightly-reports.py
It is important to identify the MediaUpload as a text/csv (because
that's what it is), and then identify the target Google file as a
Gsheet (so that Google will convert from the CSV to a Sheet).
=> stewardship-2021: fix CSV uploads

media/windows/calendar-reservations/calendar-reservations.py
When the bot accepts or declines a calendar reservation, be sure to
send an email back to the event owner letting them know.
FYI @toQhom I added in the "send updates" functionality we talked about on the phone.
=> calendar-reservations: send email replies

media/linux/pds-sqlite3-queries/sync-google-group.py, media/windows/ECC-MQTT-IoT/ECC_MQTT_IoT_SQLite.py, media/windows/copy-mp3s-to-google-drive/find-and-copy.py, media/windows/email-patch-tuesday/patch-tuesday.py, media/windows/email-timecard-twice-month/email-timecard.py, pds-queries/2020-spring-census/make-and-send-emails.py, pds-queries/2021-stewardship/make-and-send-emails.py, pds-queries/2021-stewardship/nightly-reports.py
Specify that our local hostname is "epiphanycatholicchurch.org" so
that we never "ehlo" with 127.0.0.1 if we're on a host with no
internet IP address that has no reverse hostname available (because
Google will immediately disconnect if you "ehlo 127.0.0.1").
=> python: update SMTP_SSL usage

pds-queries/2021-stewardship/make-and-send-emails.py
You can apparently have a fund rate but no total (just discovered this
with a Family who was a non-parishioner for several years, but was
literally just switched to parishioner status), so protect for that
case.
=> eStewardship: protect FDFundTotal

pds-sandbox/refresh-sandbox.py
Simple script that staff can execute to re-create their PDS sandbox by
copying over all the data files from the \\media-o3020 server to a
specific location on C:\ (thereby overwriting their old sandbox data)
and then setting the color scheme to "Pumpkin" so that it's obvious that
it's the sandbox and not the production database.
=> refresh-sandbox: make a new PDS sandbox

.gitignore, python/ECC.py, python/requirements.txt, slack/requirements.txt, slack/runner.py
See the individual commit messages for details.
In short:
1. Add capability to log to Slack for `log.critical()` errors in `ECC.setup_logging()`.
1. Add `runner.py` to execute automation scripts and log to Slack upon error.  Also add the capability to log to Slack upon success, specifically for the use case of "proof of life" (i.e., that the automation is nominally working correctly and logging to Slack).
FYI @fowlerk
=> Slack notifications

media/linux/run.sh
Sometimes Google API calls take *minutes* for no apparent reason.
Rather than fight it, just let the timeout be longer -- it won't cause
any harm, because the next iteration of the Linux python automation will be blocked
from executing by the lockfile, so it doesn't matter if this one takes
a while to run.
=> media/linux/run.sh: increase runner timeout

python/PDSChurch.py
It can be useful to know if a given PDS Family is a parishioner or
not. So in addition to allowing filtering of non-parishioners on the
initial query (PDSChurch.load_families_and_members(...)), also have a
PDSChurch.is_parishioner(family) function which simply returns True or
False.
=> PDSChurch.py: add is_parishioner(family) method

media/linux/pds-sqlite3-queries/sync-google-group.py
This project is now over, and the corresponding Google Group has been
deleted.
=> sync-google: remove Visual Faith group

media/linux/ecc-clear-pds-lockfile.service
We no longer use this systemd service because the lockfile is cleared
by a Windows Task Scheduler event.  Add comments explaining this.
Also fix the current path where the run-all lockfile is located these
days.
=> systemd: add clarification comments

media/linux/pds-sqlite3-queries/sync-google-group.py
Only look for chairs of ministries that start with "ddd-" or
"ddd[ABC]", where "d" is a digit.  All other ministries are defunct.
=> sync-google: exclude defunct ministry

pds-queries/utilities/print-keywords.py, python/PDSChurch.py
Small Python utility to print out all PDS keywords (both member
keywords and family keywords), and indicate if there are no
members/families who have that keyword.
=> print-keywords.py: new utility

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
Fix typo in name of a ministry.
=> ministry-rosters.py: fix typo

media/linux/pds-sqlite3-queries/sync-google-group.py
Change all the notification email addresses for the Formation-related
groups to formation@ecc.
=> sync-google-group: update Formation notification email

media/linux/pds-sqlite3-queries/sync-google-group.py
Effectively revert b32e606ce, but with a new ministry name.  The
"451-Livestream Team" ministry no longer exists (because the
livestream team is not a "ministry") -- that's why b32e606ce removed
the linkage between the 451 ministry and the livestream-team@ecc
Google Group.  But we do still need to track the members of the
Livestream Team in PDS, and we want to have a Google Group for them.
So the "451-Livestream Team" ministry has been renamed to be
"WG-Livestream Team" (WG = "Working Group").
=> sync-google-group: add livestream team

media/linux/pds-sqlite3-queries/ppc-feedback-google-group.py
Ensure to make the email addresses that are read in from the Google
Sheet to be lower case so that we can reliably compare them to the
Google Group members.
=> ppc-feedback: compare lower case emails

media/linux/pds-sqlite3-queries/sync-google-group.py
Update several notification email addresses in sync-google-groups.
Additionally, move the Name Badges sync entry to a better location.
=> sync-google-groups: update notification emails

media/linux/pds-sqlite3-queries/sync-google-group.py
This group was removed in the 2022 google groups audit (it has
effectively been replaced by the Ministry Scheduler Pro app).
=> sync-google-group: remove communion-ministers-coordinators@ecc

media/linux/pds-sqlite3-queries/sync-google-group.py
Add top-level ministries for 309, 313, 316, and 318.
As of August 2022, it has been decided that we are removing the
A/B/C/D ministries altogether.  Data has been sent to the parish admin
assistant to update PDS such that all Members who are in the A/B/C/D
sub-ministries are *also* in the no-letter ministries.  This will
allow us to remove the A/B/C/D ministries from PDS altogether.
During this transition, sync the Google Groups to the A/B/C/D
ministries *and* the no-letter ministry.  A future commit will remove
syncing against the A/B/C/D ministries.
=> sync-google-groups: update

media/linux/pds-sqlite3-queries/create-ministry-rosters.py
Additionally, the Livestream Team was moved from a Ministry to a Keyword.  Add functionality to make rosters from a Keyword.
=> create-ministry-rosters: update for 2022 Stewardship ministry names

media/linux/ricoh/requirements.txt
Add some missing Python packages to the linux/ricoh/requirements.txt file.
=> linux/ricoh: update requirements.txt

media/linux/pds-sqlite3-queries/sync-google-group.py
The Community Life Coordinator position has been morphed into the Pastoral Associate for Parish Life.  Update the email addresses to match.
=> sync-google-groups: change email for Parish life

media/linux/pds-sqlite3-queries/sync-google-group.py
Use the Youth role email address instead of an individual email address.
=> sync-google-group: use role email address

media/linux/calendar-reservations/calendar-reservations.py
If a Google calendar event does not have a title, refused to accept it (but do not crash!).
=> calendar-reservations: handle events without titles

media/windows/server-backups/google-backups.bat
Add a little intelligence to the server backups batch script to try to ensure that we are really robocopying the DSX thumb drive to the backup location, not some other disk.
Also, parameterize the target location, just in case we ever need to move them to a different place.
=> server-backups.bat: be smarter about Windows backups

media/linux/calendar-reservations/calendar-reservations.py
We have consolidated the reservable CC rooms from E, F, G, H, I, J, K, L L to F-H and I-K.  Hence, there are now only 2 CC Google calendars; remove all the rest.
=> calendar-reservations.py: remove now-deleted calendars

pds-sandbox/refresh-sandbox.py
* Skip copying *.lck files, because those may open by other network users, which would cause xcopy to error when trying to read/copy them.
* Only print the "success" message if it actually succeeded.
=> refresh-sandbox: make it more robust

media/linux/pds-sqlite3-queries/gsheet-driven-google-group.py
A trivial missing computation accidentally sent the wrong wording to the addressees who are being removed from the Google Group.  Add the missing line to properly compute the list of email addresses that is insertted into the email body text indicating who will no longer be receiving the Group emails.
=> gsheet-driven-google-group.py: fix email wording

media/linux/pds-sqlite3-queries/create-communion-ministry-reports.py
Remove a column that isn't needed any more (we no longer use the communion ministry sub-ministries, and therefore no longer need to report on it).
=> create-communion-ministry-reports: remove unneeded column

media/linux/calendar-reservations/calendar-reservations.py
The functionality of the musicians Google calendar is now in Ministry Scheduler Pro, redering that calendar effectively useless.  As such, the Music minister asked us to delete the old/stale Google calendar today.
=> calendar-reservations.py: Remove musicians calendar

media/linux/pds-sqlite3-queries/create-family-lists.py
It turns out that mail merge functionality doesn't like it when there's more than 1 header row.  So ditch all the extra header rows in the family lists google sheet.
=> create-familiy-lists.py: remove extra rows

media/linux/pds-sqlite3-queries/gsheet-driven-google-group.py
Remove some hard-coded name-based email addresses and replace them with their role-based equivalents.
=> Python automation: use role-based email addresses

media/linux/google-group-audit/requirements.txt
This was accidentally sitting around uncommitted; we now need the httplib2 module for the annual Google Groups audit python script.
=> Add a python module to requirements.txt

media/linux/google-group-audit/annual-google-group-audit.py
Check all Google Shared Drives that the credential has access to and see if each Google Group is being used as permissions in that GSD.
=> Annual google group audit: check if groups used for permissions

media/linux/ps-queries/create-ministry-rosters.py
When sorting by name, ensure that we don't accidentally collapse Members with the same name into a single listing.
=> create-ministry-rosters: fix duplicate names

python/ParishSoftv2.py
The ministry sync was incorrectly ignoring ministry record start/end dates.  Make sure to take those into account when computing the sync to google groups by only listing the member's active ministries on the member dictionary.
=> sync-google-group.py: abide by ministry start/end dates

python/ParishSoftv2.py
Should use ">=" instead of ">" date comparison to today to ensure to include the last day of membership in a ministry.
=> ParishSoftv2.py: include the last day of a ministry

python/ParishSoftv2.py
1. Remove duplicate and dead code (filtering member from member workgroups twice, and filtering family from member workgroup)
2. Handle non-existent cache directories
3. Properly filter deleted members
=> ParishSoftv2: cleanups and corrections

media/linux/ps-queries/sync-google-group.py, python/ParishSoftv2.py
Handle if a Member's emailAddress field has multiple email addresses separated by ";".
NOTE: The Family email address field is "eMailAddress" while the Member email address field is "emailAddress".  Sigh.
=> ParishSoft: handle Members with multiple email addresses

python/ParishSoftv2.py
Split ;-delimited lists of the normalized email addresses to Python lists.
=> ParishSoft: properly normalize all email addresses to lower case

python/ParishSoftv2.py
Fix lower-case normalization of email addresses.  Also handle multi-email address cases in Family and Member WorkGroups.
=> ParishSoft: more Member multi-email address handling

python/ParishSoftv2.py
Add one more location where a Member's email address could be empty (i.e., None).
=> ParishSoftv2: protect against empty email field

python/ParishSoftv2.py
It is possible that a Member is added to a Member WorkGroup but then subsequently leaves ECC and gets registered at some other parish.  In this case, it looks like PS will wholly remove that Member from ECC's history -- i.e., there will be no more Member DUID at ECC for this Member any more (vs. just being inactive).  Strange, but true.
Regardless, make sure to handle this case.
=> ParishSoftv2.py: handle corner case when Members leave

.github/workflows/ecobee-google-calendar-control.yaml
I'm not entirely sure of GitHub's permissions surrounding existing GitHub Actions.  So let's make a dummy GitHub Action on `main` that has the same workflows and steps as what we're doing on the PR and see if that allows the PR version to run.
=> Make the Ecobee GitHub Action have the same steps as the final

.github/workflows/ecobee-google-calendar-control.yaml
"pull_request_target" specifically runs the GitHub Action workflow from the PR base branch, not the PR branch.  That defeats the point of allowing a PR to debug the GitHub Action workflow YAML file.
=> Allow the Ecobee GitHub Action to run on "pull_request"
